version: "3.5"

services:
  api01: &api
    image: rogeralbinoi/rinha-backend-2024-q1:latest
    hostname: api01
    env_file: .env
    restart: on-failure
    
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api 
    hostname: api02
    env_file: .env
    restart: on-failure
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    env_file: .env
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
    command: postgres -c max_connections=300 -c effective_io_concurrency=196

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

